### ISSUE TITLE
Figure list last updated on 20 July 2020

### ISSUE THREAD

**Issue by calvinize** [CherryPerry/Amiami-android-app#42]
Hi, first of all, I would like to express my gratitude for creating this app. It's very easy to use and has served me very well these past years.

Although my experience with the app has been flawless up till now, it saddens me that I've encountered an issue with the app lately, as my app suddenly stopped updating for new figures after 20 July 2020. I've refreshed it multiple times but it's still not updating. Did anything happen that broke the app's scraping?

Here's a screenshot.
![Screenshot_20200813-153704](https://user-images.githubusercontent.com/24759672/90113243-3d74c480-dd7b-11ea-9955-192915623350.jpg)

**Comment by CherryPerry** [comment]
Sorry, it happens sometimes. Just report such issues by GitHub or email please, I will restart server.
Now it works as expected.

**Comment by calvinize** [comment]
Noted, and thank you. It's working properly again.
