### ISSUE TITLE
Figure list stopped updating since 12 Oct 2021

### ISSUE THREAD

**Issue by calvinize** [CherryPerry/Amiami-android-app#46]
Hi, the figure list in my app stopped updating since 12 Oct 2021. Please do your magic. Thanks!

**Comment by CherryPerry** [comment]
Restarted, should be fine now.
Finally discovered the issue, will fix it soon https://github.com/CherryPerry/Amiami-kotlin-backend/issues/2.

**Comment by calvinize** [comment]
Awesome! Thank you for your fine work :D
