### ISSUE TITLE
Tile view is no longer available.

### ISSUE THREAD

**Issue by wargry** [CherryPerry/Amiami-android-app#7]
The grid display with only the photos is no available.

**Comment by CherryPerry** [comment]
Show name option will be available in settings. 
Long press to see name.

![device-2018-08-18-220231](https://user-images.githubusercontent.com/9081555/44302519-0ce82480-a333-11e8-94f4-536ee5a1164c.png)
![device-2018-08-18-220256](https://user-images.githubusercontent.com/9081555/44302520-0eb1e800-a333-11e8-8a29-63cd63a96436.png)

**Comment by CherryPerry** [comment]
Done https://github.com/CherryPerry/Amiami-android-app/commit/3551fbaad086acaa87b4741ed68b41d6493a5fb3
